shapes:
  video:
    T: 16
    H: 32
    W: 32
    C: 1
  patches:
    pt: 2
    ph: 4
    pw: 4

data:
  n_train_samples: 100_000_000
  n_val_samples: 1_000
  seed: 42
  pad_token: 0
  prompt_len: 8

model:
  noise_scheduler_steps: 1000
  prompt_vocab_size: 42  # actually 37 but reserved some tokens
  hidden_dim: 128
  num_layers: 6
  num_heads: 8
  mlp_ratio: 4

training:
  lr: 4.e-4
  precision: "32"
  max_epochs: 6
  batch_size: 128
  num_workers: 8
  prefetch_factor: 128
  devices: 8

  save_path: "checkpoints"